# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Wanderlist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wanderlist
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'FBSDKCoreKit'
pod 'GoogleSignIn'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

end
