# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoaPodsAppV1' do
pod 'SwiftyJSON', '~> 3.1.1'
pod 'Alamofire', '~> 4.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsAppV1

end
