# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CheapMessengerAppV1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'
pod 'Flurry-iOS-SDK/FlurrySDK'
#pod 'Flurry-iOS-SDK/FlurryAds'

  # Pods for CheapMessengerAppV1

end
